services:
  api:
    container_name: task_api
    build:
      context: .
      dockerfile: Dockerfile
    image: task-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://taskuser:taskpassword@db:5432/taskdb
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  db:
    container_name: task_db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
      POSTGRES_DB: taskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
